### ISSUE TITLE
Animation Data modified by update (tweenKeys and unmaptweenkeys)

### ISSUE THREAD

**Issue by wighawag** [Trixt0r/spriter#17]
Hi,

This is not really an issue but more a question to understand your Spriter implementation. 
it is quite well documented but I have few questions :

I can see that Entity store the data from the scml. This include the Animation class. What I don't get is that this Animation class have its data modified on the update method.

Is the tweenKeys, unmaptweenkeys fields used for calculation only ? Why did you chose to put them in Animation (which should be static as it represent the SCML) and not in Player  (which is the instantiation of an Entity)?

Thanks

**Comment by Trixt0r** [comment]
tweenedKeys and unmappedTweenedKeys are used to store the calculated data and to render the objects properly later on. I put them into the Animation class because of reusability. If I would put all the update logic into the Player class, it would have too much code to maintain at the same spot, which may cause many bugs. That was the problem with the library last year before I refactored it.
