### ISSUE TITLE
Float allocations in case of Bezier curves

### ISSUE THREAD

**Issue by denisk20** [Trixt0r/spriter#21]
Since `Calculator#solveCubic` returns `Float` instead of `float` it generates many `Float` objects when there is Bezier curve which affects performance on Android devices. I'm not sure how to properly solve this: we can't just return `0` instead of `null` to indicate that there is no solution for given cubic equation since `0` can be the solution itself when `d = 0`.

**Comment by Trixt0r** [comment]
I am going to take a look at this problem a bit closer.

**Comment by denisk20** [comment]
Same concerns apply to `Calculator#solveQuadratic`.

**Comment by denisk20** [comment]
Actually I've got a question about `Calculator#solveQuadratic`: why are there checks for the result to be in `[0, 1]` range? If both roots are outside of this range you return `null`, which is not correct from math point of view since such equation always have 2 roots (unless `a = 0`, which should probably be checked). And in this method the value of `sqrt(squaredB - fourAC)` should probably be cached - square root is a pretty CPU-intense calculation.

**Comment by Trixt0r** [comment]
The range check is done, because we only require values between 0 and 1 (same for `Calculator#solveCubic`).

I guess I did this check because I didn't want to do the checks in an other place. Maybe I can move the check into the `Curve` class, where it is needed. This would solve the `Float` object problem at least in the `Calculator` class.

The question is, whether this creates issues in the `Curve` class. Let me see...

I don't know if caching results of `Math.sqrt` is a good solution, since this may cause the RAM to blow up unnecessarily. Do you know how fast this method works on an average Android device?

**Comment by denisk20** [comment]
@Trixt0r Sorry, I wasn't clear about caching: I just meant to extract the result of `sqrt(squaredB - fourAC)` into a local variable in `Calculator#solveCubic` to avoid calculating it twice.
If the check can be moved into a common place it will be great. It would probably be something like this in `Curve`

    if(cubicSolution < 0 || cubicSolution > 1) cubicSolution = lastCubicSolution;

instead of existing

    if(cubicSolution == null) cubicSolution = lastCubicSolution;

And `solveCubic` can be modified to return the first root which falls into `[0, 1]` range, or the first/last root if none falls into `[0, 1]`.
I might be missing something so let me know if that's the case.

**Comment by denisk20** [comment]
@Trixt0r Created a pull request, please take a look.

**Comment by Trixt0r** [comment]
Looks good.
