### ISSUE TITLE
CharacterMaps can't be applied as in the readme.

### ISSUE THREAD

**Issue by phunni** [Trixt0r/spriter#43]
I don't know if anyone is looking after this project anymore or if it's abandoned. On the off chance, however, that anyone sees this - here's my problem.

The readme says that applying a charactermap is as simple as:

`CharacterMap map = player.getEntity().getCharacterMap("name of your char map");
player.characterMap = map;`

However, there is no such property in the Player class. There is a characterMaps - which is an array. I tried setting my CharacterMap to the first item in what was otherwise an empty array, but it didn't work. Nor did I really expect it to if I'm honest...

As such, I now have no idea if there is any way to set different character maps active using this library...

**Comment by Trixt0r** [comment]
I barely remember this...

A player can hold an array of character maps.
While drawing the player, character maps with a higher array index, override the previous ones.

As I remember correctly this is the way spriter handles character maps. You can lay character maps on top of each other without overriding specific sprites, I suppose.

You can also checkout the example with character maps: https://github.com/Trixt0r/spriter-examples/blob/master/desktop/src/com/brashmonkey/spriter/examples/desktop/CharacterMapTest.java

If I find time, I may fix the docs. Otherwise you are also welcome to submit a pull request for a README change :)
